server:
  port: 8086

spring:
  application:
    name: rabbitmq-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: '*'
